### ISSUE TITLE
Build a skeleton for Area A homepage

### ISSUE THREAD

**Issue by budschi** [FAIRmat-Experimental/Area_A_sample_preparation#2]
Build a skeleton for Area A homepage so that we can start adding content for the different sub-pages

**Comment by domna** [comment]
@budschi @aalbino2 @tomio13 @MartinAlbrechtIKZ
The skeleton is finished and the page can be found at https://fairmat-experimental.github.io/Area_A_sample_preparation/
I created four subpages for the four tasks which are in the respective md file `task_ax.md`. The `index.md` file holds the overview. You may add additional md file which get added to the navigation bar automatically.

The general configuration variables (site names, links etc.) are in the `_config.yml` file.
The template is just a simple default template and I would just keep it for now until we receive the template from the FAIRmat Webdesigners (#5). @budschi I used the email address area-a@fairmat-nfdi.eu which obviously does not exist. However, I thought if it would maybe be possible to create such generic emails for the different areas. I think it could be nice, what do you think?

You can also develop on the page locally with Jekyll, see the [github docs](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll) for help on that (also feel free to ask me if you run in any problems). If you commit changes into doc the page gets updated automatically (takes around 3 to 5 minutes, so be patient ;)

**Comment by budschi** [comment]
Thank you @domna ! 
I justed asked Victoria if we can have such an email.
Also, I tested to add a new sub page by adding the "Publications" page.
