### ISSUE TITLE
Sidebar: link to NOMAD and FAIRmat 

### ISSUE THREAD

**Issue by budschi** [FAIRmat-Experimental/Area_A_sample_preparation#9]
Add link to [NOMAD ](https://nomad-lab.eu/) and [FAIRmat ](https://www.fairmat-nfdi.eu/fairmat/consortium)homepage in the sidebar

**Comment by aalbino2** [comment]
not relevant anymore, as our documentation will be embedded in the main fairmat websites, as discussed during the project meeting 14-16 november 2022
